"""The replay guide on the site, taken from dmipy-sim's ``docs/replay-guide/``.

The guide is written and tested in the engine's repository (``tests/test_replay_guide.py`` there runs every
block); the site carries a copy under ``docs/replay/`` so that its blocks run in the site's CI too and the
pages build with the rest. ``README.md`` becomes ``index.md`` and links to it follow; every page starts with a
comment naming the commit it was taken from. Edit the guide in dmipy-sim, then regenerate here.

Run:  python tools/gen_replay_guide.py            (clones dmrai-lab/dmipy-sim at main into a temporary directory)
      DMIPY_SIM_SRC=/path/to/dmipy-sim python tools/gen_replay_guide.py     (a local checkout)
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "replay"
REPO = "https://github.com/dmrai-lab/dmipy-sim"
GUIDE = Path("docs") / "replay-guide"


def source() -> tuple[Path, str]:
    """The checkout to read from and the commit it is at."""
    src = os.environ.get("DMIPY_SIM_SRC")
    if src:
        path = Path(src).resolve()
    else:
        path = Path(tempfile.mkdtemp(prefix="dmipy-sim-")) / "dmipy-sim"
        subprocess.run(["git", "clone", "-q", "--depth", "1", "--branch", "main", REPO, str(path)], check=True)
    sha = subprocess.run(["git", "-C", str(path), "rev-parse", "HEAD"], check=True, capture_output=True, text=True).stdout.strip()
    return path, sha


def convert(text: str, sha: str) -> str:
    text = re.sub(r"\(README\.md\)", "(index.md)", text)
    text = re.sub(r"\((\.\./)?README\.md\)", "(index.md)", text)
    text = text.replace("(`tests/test_replay_guide.py`)", "(`tests/test_replay_guide.py` in dmipy-sim, and `tools/run_snippets.py` on this site)")
    head = f"<!-- generated by tools/gen_replay_guide.py from dmrai-lab/dmipy-sim@{sha[:12]} docs/replay-guide; edit it there -->\n"
    return head + text


def main() -> int:
    path, sha = source()
    guide = path / GUIDE
    pages = sorted(guide.rglob("*.md"))
    if not pages:
        print(f"no guide under {guide}", file=sys.stderr)
        return 1
    if OUT.exists():
        shutil.rmtree(OUT)
    for page in pages:
        rel = page.relative_to(guide)
        rel = Path("index.md") if rel.name == "README.md" and rel.parent == Path(".") else rel
        dest = OUT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(convert(page.read_text(encoding="utf-8"), sha), encoding="utf-8")
        print(f"{rel}")
    print(f"{len(pages)} pages from dmipy-sim@{sha[:12]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
